meta_name: "Vida do Livro"
meta_title: "Vida do Livro - O Curso para entender o mercado editorial"
meta_description: "Uma jornada para leitores, profissionais e curiosos do mercado editorial."
# meta_image: "cover.png" # should exist in `app/assets/images/`
